# Generated by Django 6.1.1 on 2026-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='device_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
