# Generated by Django 6.1.1 on 2026-09-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_locationrecord_browser_locationrecord_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='architecture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='bitness',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='city_district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='client_hint_platform',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='client_hint_platform_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='device_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='pixel_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='platform',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='suburb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='town',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='village',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='ward',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
