# Generated by Django 6.1.1 on 2026-09-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_locationrecord_architecture_locationrecord_bitness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
